/**
 * Extracts the curated Lucide icon set into config/icons.php so that
 * <x-icon> can render inline SVG server-side, with no client JS payload.
 *
 * Add a name to ICONS and re-run:  node scripts/build-icons.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const ICONS = [
    'house', 'layout-dashboard', 'menu', 'chevron-right', 'chevron-down', 'chevron-left',
    'chevron-up', 'external-link', 'log-out', 'search', 'settings', 'panels-top-left',
    'newspaper', 'file-text', 'files', 'folder', 'folder-tree', 'tag', 'tags', 'image',
    'images', 'video', 'book-open', 'library', 'layers', 'list', 'list-ordered', 'pencil',
    'plus', 'trash-2', 'eye', 'eye-off', 'download', 'upload', 'paperclip', 'archive',
    'copy', 'save', 'filter', 'calendar', 'clock', 'star', 'pin',
    'briefcase', 'handshake', 'clipboard-list', 'receipt', 'banknote', 'workflow',
    'circle-help', 'megaphone', 'building-2', 'map-pin',
    'phone', 'mail', 'globe', 'link',
    'users', 'user', 'user-plus', 'shield', 'shield-check', 'key-round', 'lock',
    'history', 'activity', 'database', 'server', 'circle-check', 'circle-alert',
    'triangle-alert', 'info', 'circle-slash', 'x', 'check', 'circle', 'loader-circle',
    'accessibility', 'type', 'volume-2', 'pause', 'square', 'play', 'contrast', 'palette',
    'move', 'grip-vertical', 'sun', 'moon',
    'facebook', 'instagram', 'youtube', 'twitter', 'linkedin', 'send',
    // For the social-post cards. Lucide dropped brand marks, so the platform
    // is named in text; these are the generic action glyphs beside it.
    'heart', 'message-circle', 'bookmark', 'ellipsis', 'badge-check',
    'undo-2', 'redo-2', 'maximize', 'sparkles',
];

const parts = [];
const missing = [];

for (const name of [...new Set(ICONS)].sort()) {
    const path = `node_modules/lucide-static/icons/${name}.svg`;

    if (!existsSync(path)) {
        missing.push(name);
        continue;
    }

    const body = readFileSync(path, 'utf8')
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/^[\s\S]*?<svg[^>]*>/, '')
        .replace(/<\/svg>\s*$/, '')
        .replace(/\s+/g, ' ')
        .trim();

    parts.push(`    '${name}' => '${body.replace(/'/g, "\\'")}',`);
}

if (missing.length) {
    console.warn(`Skipped unknown icons: ${missing.join(', ')}`);
}

writeFileSync(
    'config/icons.php',
    `<?php

/*
 | Inline Lucide icon bodies, keyed by the kebab-case name stored in the
 | database. Generated by scripts/build-icons.mjs - do not edit by hand.
 | Rendering happens server-side so icons need no JavaScript and survive
 | with JS disabled.
 */

return [
${parts.join('\n')}
];
`,
);

console.log(`Wrote config/icons.php with ${parts.length} icons.`);
